import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, '..');
const projectDataPath = path.join(projectRoot, 'src', 'app', 'data', 'projects.ts');
const sitemapPath = path.join(projectRoot, 'public', 'sitemap.xml');
const siteUrl = 'https://cesurpolat.dev';

const staticPages = [
  { path: '/', lastModified: '2026-08-07' }
];

const projectSource = await readFile(projectDataPath, 'utf8');
const projectPattern = /slug:\s*['"]([^'"]+)['"],\s*\r?\n\s*lastModified:\s*['"](\d{4}-\d{2}-\d{2})['"]/g;
const projects = [...projectSource.matchAll(projectPattern)].map((match) => ({
  path: `/projects/${match[1]}`,
  lastModified: match[2]
}));

if (projects.length === 0) {
  throw new Error(`No projects found in ${projectDataPath}`);
}

for (const project of projects) {
  const slug = project.path.replace('/projects/', '');
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    throw new Error(`Invalid project slug: ${slug}`);
  }

  if (Number.isNaN(Date.parse(`${project.lastModified}T00:00:00Z`))) {
    throw new Error(`Invalid lastModified date for ${slug}: ${project.lastModified}`);
  }
}

const pages = [...staticPages, ...projects];
const urlEntries = pages
  .map(({ path: pagePath, lastModified }) => {
    const location = pagePath === '/' ? `${siteUrl}/` : `${siteUrl}${pagePath}`;
    return [
      '  <url>',
      `    <loc>${location}</loc>`,
      `    <lastmod>${lastModified}</lastmod>`,
      '  </url>'
    ].join('\n');
  })
  .join('\n');

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/generate-sitemap.mjs. Do not edit manually. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  urlEntries,
  '</urlset>',
  ''
].join('\n');

let currentSitemap = '';
try {
  currentSitemap = await readFile(sitemapPath, 'utf8');
} catch (error) {
  if (error.code !== 'ENOENT') {
    throw error;
  }
}

if (currentSitemap !== sitemap) {
  await writeFile(sitemapPath, sitemap, 'utf8');
  console.log(`Generated sitemap with ${pages.length} URLs.`);
} else {
  console.log(`Sitemap is up to date with ${pages.length} URLs.`);
}
